package com.ai.aisse.core.po;

public class Hostgrouptype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostgrouptype.gtid
     *
     * @mbggenerated
     */
    private Integer gtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostgrouptype.hostgroupid
     *
     * @mbggenerated
     */
    private String hostgroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hostgrouptype.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostgrouptype.gtid
     *
     * @return the value of hostgrouptype.gtid
     *
     * @mbggenerated
     */
    public Integer getGtid() {
        return gtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostgrouptype.gtid
     *
     * @param gtid the value for hostgrouptype.gtid
     *
     * @mbggenerated
     */
    public void setGtid(Integer gtid) {
        this.gtid = gtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostgrouptype.hostgroupid
     *
     * @return the value of hostgrouptype.hostgroupid
     *
     * @mbggenerated
     */
    public String getHostgroupid() {
        return hostgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostgrouptype.hostgroupid
     *
     * @param hostgroupid the value for hostgrouptype.hostgroupid
     *
     * @mbggenerated
     */
    public void setHostgroupid(String hostgroupid) {
        this.hostgroupid = hostgroupid == null ? null : hostgroupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hostgrouptype.type
     *
     * @return the value of hostgrouptype.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hostgrouptype.type
     *
     * @param type the value for hostgrouptype.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}