package com.ai.aisse.core.po;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.renter_id
     *
     * @mbggenerated
     */
    private Integer renterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_account
     *
     * @mbggenerated
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_type
     *
     * @mbggenerated
     */
    private Byte accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.display_name
     *
     * @mbggenerated
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.origin_type
     *
     * @mbggenerated
     */
    private Byte originType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.zb_token
     *
     * @mbggenerated
     */
    private String zbToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.zb_token_update
     *
     * @mbggenerated
     */
    private Date zbTokenUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.remember_token
     *
     * @mbggenerated
     */
    private String rememberToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.renter_id
     *
     * @return the value of users.renter_id
     *
     * @mbggenerated
     */
    public Integer getRenterId() {
        return renterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.renter_id
     *
     * @param renterId the value for users.renter_id
     *
     * @mbggenerated
     */
    public void setRenterId(Integer renterId) {
        this.renterId = renterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_account
     *
     * @return the value of users.login_account
     *
     * @mbggenerated
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_account
     *
     * @param loginAccount the value for users.login_account
     *
     * @mbggenerated
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_type
     *
     * @return the value of users.account_type
     *
     * @mbggenerated
     */
    public Byte getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_type
     *
     * @param accountType the value for users.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(Byte accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.display_name
     *
     * @return the value of users.display_name
     *
     * @mbggenerated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.display_name
     *
     * @param displayName the value for users.display_name
     *
     * @mbggenerated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.origin_type
     *
     * @return the value of users.origin_type
     *
     * @mbggenerated
     */
    public Byte getOriginType() {
        return originType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.origin_type
     *
     * @param originType the value for users.origin_type
     *
     * @mbggenerated
     */
    public void setOriginType(Byte originType) {
        this.originType = originType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.zb_token
     *
     * @return the value of users.zb_token
     *
     * @mbggenerated
     */
    public String getZbToken() {
        return zbToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.zb_token
     *
     * @param zbToken the value for users.zb_token
     *
     * @mbggenerated
     */
    public void setZbToken(String zbToken) {
        this.zbToken = zbToken == null ? null : zbToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.zb_token_update
     *
     * @return the value of users.zb_token_update
     *
     * @mbggenerated
     */
    public Date getZbTokenUpdate() {
        return zbTokenUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.zb_token_update
     *
     * @param zbTokenUpdate the value for users.zb_token_update
     *
     * @mbggenerated
     */
    public void setZbTokenUpdate(Date zbTokenUpdate) {
        this.zbTokenUpdate = zbTokenUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_login_time
     *
     * @return the value of users.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_login_time
     *
     * @param lastLoginTime the value for users.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.remember_token
     *
     * @return the value of users.remember_token
     *
     * @mbggenerated
     */
    public String getRememberToken() {
        return rememberToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.remember_token
     *
     * @param rememberToken the value for users.remember_token
     *
     * @mbggenerated
     */
    public void setRememberToken(String rememberToken) {
        this.rememberToken = rememberToken == null ? null : rememberToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}