package com.ai.aisse.core.dao.mapper;

import com.ai.aisse.core.po.Hostgrouptype;

public interface HostgrouptypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostgrouptype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostgrouptype
     *
     * @mbggenerated
     */
    int insert(Hostgrouptype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostgrouptype
     *
     * @mbggenerated
     */
    int insertSelective(Hostgrouptype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostgrouptype
     *
     * @mbggenerated
     */
    Hostgrouptype selectByPrimaryKey(Integer gtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostgrouptype
     *
     * @mbggenerated
     */
    Hostgrouptype selectByGroupid(Integer hostgroupid);
    
    
    
    
    int updateByPrimaryKeySelective(Hostgrouptype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostgrouptype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hostgrouptype record);
}